import '@/styles/globals.css';

import React from 'react';

import { fontMono, fontSans } from '@/lib/fonts';
import { cn } from '@/lib/utils';
export const metadata = {
  title: '123',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable, fontMono.variable)}>
        {children}
      </body>
    </html>
  );
}
