import '@/styles/globals.css';

import React from 'react';

import { SiteFooter } from '@/components/layouts/SiteFooter';
import { ThemeProvider } from '@/components/ThemeProvider';
import { Toaster } from '@/components/ui/toaster';
import { fontMono, fontSans } from '@/lib/fonts';
import { cn } from '@/lib/utils';
export const metadata = {
  title: '123',
  description: 'Generated by create next app'
};
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable, fontMono.variable)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          <SiteFooter />
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
