name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "Setting up SSH"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy application
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "Deploying to EC2"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $USER_NAME@$SSH_HOST '
            cd /root/jin_next13-file-structure &&
            git reset --hard &&
            git checkout main &&
            git pull origin main &&
            docker-compose down &&
            docker-compose rm -fsv &&
            docker-compose up --build -d
          '
